### ISSUE TITLE
Cannot find module ~/.config/mpv/scripts/rikai-mpv/rikaichamp-backend/extension/background_search_html.js 

### ISSUE THREAD

**Issue by chibigit** [fxmarty/rikai-mpv#4]
Hi,
   I'm a bit confused about this.
Node complains that Cannot find module ~/.config/mpv/scripts/rikai-mpv/rikaichamp-backend/extension/background_search_html.js 

But, there's a background_search_html.ts  file in src but no .js files in what I downloaded.

What do I do?

thanks

**Comment by chibigit** [comment]
This is a duplicate issue

**Comment by fxmarty** [comment]
Hello, did these steps help https://github.com/fxmarty/rikai-mpv/issues/3#issuecomment-887492831 ? I tried to edit the README but I agree it is a bit involved just to install, I hope I can find a simpler solution.

**Comment by chibigit** [comment]
Yes, thank you! I couldn't get the script to work though :( 
It pops up a little blank window, beside the main mpv window, but nothing appears in it. 
I think Qt just doesn't work well on MacOS.

**Comment by fxmarty** [comment]
Ah, that's bad to hear :-(

I somewhat expected it to break on MacOS, I explicitly call a function related to X11 (here https://github.com/fxmarty/rikai-mpv/blob/main/subtitles_popup_graphics.py#L120 ), so maybe this is a problem, but I think it should be not too hard to fix. If I gets hands on a MacOS once I will have a look.

Otherwise have you tried Memento https://github.com/ripose-jp/Memento ? I never tried it, but probably it works on MacOS and could fit your need.

Edit: Maybe this would help https://github.com/oltodosel/interSubs/issues/42#issuecomment-841725012 ? There are a bunch of issues in interSubs repo related to MacOS, maybe there is a good solution there.
